BEGIN;
DROP TRIGGER IF EXISTS acquisition_event_immutable ON acquisition_event;
DROP TRIGGER IF EXISTS source_artifact_immutable ON source_artifact;
DROP FUNCTION IF EXISTS bible_os_prevent_update_delete();
DROP TABLE IF EXISTS dataset_release;
DROP TABLE IF EXISTS validation_report;
DROP TABLE IF EXISTS alignment;
DROP TABLE IF EXISTS text_unit;
DROP TABLE IF EXISTS corpus_artifact;
DROP TABLE IF EXISTS corpus;
DROP TABLE IF EXISTS passage_reference_mapping;
DROP TABLE IF EXISTS versification_reference;
DROP TABLE IF EXISTS versification_system;
DROP TABLE IF EXISTS passage;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS work;
DROP TABLE IF EXISTS source_artifact;
DROP TABLE IF EXISTS acquisition_event;
DROP TABLE IF EXISTS source;
COMMIT;
